# Generated by Django 3.0.3 on 2020-03-23 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('road_adr', models.CharField(max_length=500)),
                ('num_adr', models.CharField(max_length=500)),
                ('tel', models.CharField(max_length=13)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Register_place',
        ),
    ]
